# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SubProtocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SubProtocol.proto',
  package='signalservice',
  syntax='proto2',
  serialized_options=b'\n3org.whispersystems.signalservice.internal.websocketB\017WebSocketProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11SubProtocol.proto\x12\rsignalservice\"`\n\x17WebSocketRequestMessage\x12\x0c\n\x04verb\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x12\x0f\n\x07headers\x18\x05 \x03(\t\x12\n\n\x02id\x18\x04 \x01(\x04\"f\n\x18WebSocketResponseMessage\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06status\x18\x02 \x01(\r\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0f\n\x07headers\x18\x05 \x03(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\x0c\"\xea\x01\n\x10WebSocketMessage\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.signalservice.WebSocketMessage.Type\x12\x37\n\x07request\x18\x02 \x01(\x0b\x32&.signalservice.WebSocketRequestMessage\x12\x39\n\x08response\x18\x03 \x01(\x0b\x32\'.signalservice.WebSocketResponseMessage\".\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07REQUEST\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x42\x46\n3org.whispersystems.signalservice.internal.websocketB\x0fWebSocketProtos'
)



_WEBSOCKETMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='signalservice.WebSocketMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQUEST', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=427,
  serialized_end=473,
)
_sym_db.RegisterEnumDescriptor(_WEBSOCKETMESSAGE_TYPE)


_WEBSOCKETREQUESTMESSAGE = _descriptor.Descriptor(
  name='WebSocketRequestMessage',
  full_name='signalservice.WebSocketRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='verb', full_name='signalservice.WebSocketRequestMessage.verb', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='signalservice.WebSocketRequestMessage.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='signalservice.WebSocketRequestMessage.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='signalservice.WebSocketRequestMessage.headers', index=3,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='signalservice.WebSocketRequestMessage.id', index=4,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=132,
)


_WEBSOCKETRESPONSEMESSAGE = _descriptor.Descriptor(
  name='WebSocketResponseMessage',
  full_name='signalservice.WebSocketResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='signalservice.WebSocketResponseMessage.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='signalservice.WebSocketResponseMessage.status', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='signalservice.WebSocketResponseMessage.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='signalservice.WebSocketResponseMessage.headers', index=3,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='signalservice.WebSocketResponseMessage.body', index=4,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=236,
)


_WEBSOCKETMESSAGE = _descriptor.Descriptor(
  name='WebSocketMessage',
  full_name='signalservice.WebSocketMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='signalservice.WebSocketMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='signalservice.WebSocketMessage.request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='signalservice.WebSocketMessage.response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WEBSOCKETMESSAGE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=473,
)

_WEBSOCKETMESSAGE.fields_by_name['type'].enum_type = _WEBSOCKETMESSAGE_TYPE
_WEBSOCKETMESSAGE.fields_by_name['request'].message_type = _WEBSOCKETREQUESTMESSAGE
_WEBSOCKETMESSAGE.fields_by_name['response'].message_type = _WEBSOCKETRESPONSEMESSAGE
_WEBSOCKETMESSAGE_TYPE.containing_type = _WEBSOCKETMESSAGE
DESCRIPTOR.message_types_by_name['WebSocketRequestMessage'] = _WEBSOCKETREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['WebSocketResponseMessage'] = _WEBSOCKETRESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['WebSocketMessage'] = _WEBSOCKETMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WebSocketRequestMessage = _reflection.GeneratedProtocolMessageType('WebSocketRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _WEBSOCKETREQUESTMESSAGE,
  '__module__' : 'SubProtocol_pb2'
  # @@protoc_insertion_point(class_scope:signalservice.WebSocketRequestMessage)
  })
_sym_db.RegisterMessage(WebSocketRequestMessage)

WebSocketResponseMessage = _reflection.GeneratedProtocolMessageType('WebSocketResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _WEBSOCKETRESPONSEMESSAGE,
  '__module__' : 'SubProtocol_pb2'
  # @@protoc_insertion_point(class_scope:signalservice.WebSocketResponseMessage)
  })
_sym_db.RegisterMessage(WebSocketResponseMessage)

WebSocketMessage = _reflection.GeneratedProtocolMessageType('WebSocketMessage', (_message.Message,), {
  'DESCRIPTOR' : _WEBSOCKETMESSAGE,
  '__module__' : 'SubProtocol_pb2'
  # @@protoc_insertion_point(class_scope:signalservice.WebSocketMessage)
  })
_sym_db.RegisterMessage(WebSocketMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
